#!/bin/bash -e
cd $(dirname $0)/..

ORIGINAL_TEMPLATE_PATH=./deployment/cloudformation/template.json
COMPILED_TEMPLATE_PATH=./deployment/cloudformation/compiled-template.json

AWS_REGION=cn-north-1
STACK_NAME=ols-api
S3_BUCKET=beijing-nho-deployment

./gradlew clean
./gradlew bootJar

java -jar ./build/libs/ols-api-0.0.1.jar